import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const API='https://pokeapi.co/api/v2/pokemon';
const TOTAL=1025;
const fallbackNames=['bulbasaur','charmander','squirtle','pikachu','eevee','snorlax','gengar','lucario','greninja','mewtwo','charizard','blastoise','venusaur','dragonite','gardevoir','rayquaza','ditto','zorua','umbreon','sylveon'];
function idFromName(name){return Number(name?.split('-')[0])||0}
function sprite(id){return id?`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`:''}
function fusionName(a,b){return `${a.name.slice(0,Math.ceil(a.name.length/2))}${b.name.slice(Math.floor(b.name.length/2))}`}
function App(){
 const [catalog,setCatalog]=useState([]);const [a,setA]=useState(null);const [b,setB]=useState(null);const [queryA,setQueryA]=useState('');const [queryB,setQueryB]=useState('');const [result,setResult]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [dark,setDark]=useState(true);
 useEffect(()=>{fetch(`${API}?limit=${TOTAL}`).then(r=>r.json()).then(d=>{setCatalog(d.results.map((x,i)=>({name:x.name,id:i+1})));setLoading(false)}).catch(()=>{setCatalog(fallbackNames.map((name,i)=>({name,id:idFromName(name)||i+1})));setLoading(false);setError('Live Pokédex unavailable — using starter catalog.')})},[]);
 const filteredA=useMemo(()=>filter(catalog,queryA),[catalog,queryA]);const filteredB=useMemo(()=>filter(catalog,queryB),[catalog,queryB]);
 function generate(x=a,y=b){if(!x||!y){setError('Choose two Pokémon first.');return}setError('');setResult({a:x,b:y,name:fusionName(x,y),idA:x.id,idB:y.id});history.replaceState({},'',`/pokemon-fusion/${x.name}-${y.name}`)}
 function random(){if(!catalog.length)return;const x=catalog[Math.floor(Math.random()*catalog.length)],y=catalog[Math.floor(Math.random()*catalog.length)];setA(x);setB(y);setQueryA(x.name);setQueryB(y.name);generate(x,y)}
 async function share(){if(!result)return;const url=location.href;try{await navigator.clipboard.writeText(url);setError('Fusion link copied to clipboard.')}catch{setError(url)}}
 function download(){if(!result)return;const canvas=document.createElement('canvas');canvas.width=900;canvas.height=520;const ctx=canvas.getContext('2d');ctx.fillStyle='#090b18';ctx.fillRect(0,0,900,520);ctx.fillStyle='#fff';ctx.font='700 34px Inter,Arial';ctx.fillText(result.name.toUpperCase(),50,70);ctx.font='20px Inter,Arial';ctx.fillStyle='#a9b1c6';ctx.fillText(`${result.a.name} × ${result.b.name}`,50,105);Promise.all([loadImage(sprite(result.idA)),loadImage(sprite(result.idB))]).then(([ia,ib])=>{ctx.drawImage(ia,80,140,300,300);ctx.drawImage(ib,520,140,300,300);const link=document.createElement('a');link.download=`${result.name}.png`;link.href=canvas.toDataURL('image/png');link.click()})}
 return <div className={dark?'app dark':'app'}><header className="nav"><div className="brand"><span className="pokeball">◓</span><span>Poke<span>Fusion</span></span></div><nav><a href="#generator">Generator</a><a href="#how">How it works</a><a href="#explore">Explore</a></nav><button className="icon" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?'☀':'☾'}</button></header>
 <main><section className="hero"><div className="eyebrow">POKÉMON FUSION LAB · MVP</div><h1>Two Pokémon.<br/><em>One wild fusion.</em></h1><p>Mix any two Pokémon, discover a new name and share your creation.</p><div className="hero-actions"><a className="primary" href="#generator">Start fusing <span>→</span></a><button className="ghost" onClick={random}>⚡ Random fusion</button></div></section>
 <section id="generator" className="panel"><div className="panel-head"><div><span className="step">01</span><h2>Choose your Pokémon</h2><p>Pick a head and body. Your fusion is generated instantly.</p></div><button className="random" onClick={random}>⤨ Surprise me</button></div><div className="selectors"><Picker label="POKÉMON A" value={a} query={queryA} setQuery={setQueryA} setValue={setA} items={filteredA} loading={loading}/><div className="plus">+</div><Picker label="POKÉMON B" value={b} query={queryB} setQuery={setQueryB} setValue={setB} items={filteredB} loading={loading}/></div><button className="generate" onClick={()=>generate()}>Create fusion <span>✦</span></button>{error&&<div className="notice">{error}</div>}</section>
 {result&&<section className="result"><div className="result-copy"><span className="step">02 · RESULT</span><h2>{result.name}</h2><p>{result.a.name} + {result.b.name}</p><div className="result-actions"><button className="primary" onClick={download}>↓ Download</button><button className="ghost" onClick={share}>↗ Share</button></div></div><div className="fusion-stage"><div className="orb orb-a"></div><div className="orb orb-b"></div><img src={sprite(result.idA)} alt={result.a.name}/><div className="fusion-mark">✦</div><img src={sprite(result.idB)} alt={result.b.name}/></div></section>}
 <section id="how" className="features"><Feature n="01" title="Pick two" text="Search the full Pokédex and choose any pair."/><Feature n="02" title="Fuse instantly" text="The MVP combines the pair into a shareable fusion identity."/><Feature n="03" title="Share it" text="Download your result or copy its unique fusion URL."/></section>
 <section id="explore" className="seo"><span className="step">EXPLORE THE LAB</span><h2>Pokémon fusion, built for discovery.</h2><p>Browse combinations, create memorable names, and build a collection of your favorite fusions. The route structure is ready for programmatic fusion pages and SEO expansion.</p></section></main><footer><div className="brand"><span className="pokeball">◓</span><span>Poke<span>Fusion</span></span></div><span>Original fan-made fusion experience · Not affiliated with Nintendo, Game Freak or The Pokémon Company.</span></footer></div>}
function filter(items,q){if(!q)return items.slice(0,8);const s=q.toLowerCase().trim();return items.filter(x=>x.name.includes(s)).slice(0,8)}
function Picker({label,value,query,setQuery,setValue,items,loading}){return <div className="picker"><label>{label}</label><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Pokémon..."/><kbd>⌘ K</kbd></div><div className="choices">{loading?<div className="empty">Loading Pokédex…</div>:items.map(x=><button className={value?.id===x.id?'choice active':'choice'} key={x.id} onClick={()=>{setValue(x);setQuery(x.name)}}><img src={sprite(x.id)} alt=""/><span>{x.name}</span><small>#{String(x.id).padStart(3,'0')}</small></button>)}{!loading&&!items.length&&<div className="empty">No Pokémon found.</div>}</div></div>}
function Feature({n,title,text}){return <article className="feature"><span>{n}</span><h3>{title}</h3><p>{text}</p></article>}
function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}
createRoot(document.getElementById('root')).render(<App/>);
