import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const API='https://pokeapi.co/api/v2/pokemon';const TOTAL=1025;
const fallbackNames=['bulbasaur','charmander','squirtle','pikachu','eevee','snorlax','gengar','lucario','greninja','mewtwo','charizard','blastoise','venusaur','dragonite','gardevoir','rayquaza','ditto','zorua','umbreon','sylveon'];
function idFromName(n){return Number(n?.split('-')[0])||0} function sprite(id){return id?`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`:''} function fusionName(a,b){return `${a.name.slice(0,Math.ceil(a.name.length/2))}${b.name.slice(Math.floor(b.name.length/2))}`}
const copy={
 en:{title:'Pokémon Fusion Generator — Create & Share Pokémon Fusions',desc:'Create unique Pokémon fusions online. Combine any two Pokémon, generate a fusion name, download your creation, and share it with friends.',h1:'Pokémon Fusion Generator',intro:'Create your own Pokémon fusion online by combining two Pokémon. Pick your favorites, generate a wild fusion name, download the result, and share your creation.',how:'How to Use the Pokémon Fusion Generator',howText:'Choose two Pokémon from the Pokédex, then create your fusion instantly. Try random combinations when you want inspiration, and use the share button to send a unique fusion URL to friends.',what:'What Is a Pokémon Fusion?',whatText:'A Pokémon fusion combines two Pokémon into one creative concept. PokeFusion is a fan-made online tool designed for quick experimentation, discovery, and sharing.',faq:'Pokémon Fusion FAQ',q1:'Is PokeFusion free?',a1:'Yes. The PokeFusion web generator is free to use in your browser.',q2:'Can I combine any two Pokémon?',a2:'The generator can search the available Pokédex catalog and combine two selected Pokémon into a fusion result.',q3:'Can I share a fusion?',a3:'Yes. Each generated pair can use a clean fusion URL that you can copy and share.'},
 fr:{title:'Générateur de fusion Pokémon — Créez vos propres fusions',desc:'Créez une fusion Pokémon en ligne. Combinez deux Pokémon, générez un nom de fusion, téléchargez votre création et partagez-la.',h1:'Générateur de fusion Pokémon',intro:'Créez votre propre fusion Pokémon en combinant deux Pokémon. Choisissez vos favoris, générez une fusion, téléchargez le résultat et partagez votre création.',how:'Comment utiliser le générateur de fusion Pokémon',howText:'Choisissez deux Pokémon dans le Pokédex, puis créez votre fusion instantanément. Essayez une combinaison aléatoire pour trouver de nouvelles idées et partagez votre fusion avec un lien unique.',what:'Qu’est-ce qu’une fusion Pokémon ?',whatText:'Une fusion Pokémon combine deux Pokémon en un concept créatif. PokeFusion est un outil fan-made conçu pour expérimenter, découvrir des combinaisons et les partager.',faq:'FAQ sur les fusions Pokémon',q1:'PokeFusion est-il gratuit ?',a1:'Oui. Le générateur PokeFusion est gratuit et fonctionne directement dans votre navigateur.',q2:'Puis-je combiner deux Pokémon ?',a2:'Oui. Recherchez les Pokémon disponibles dans le Pokédex et sélectionnez deux Pokémon pour créer une fusion.',q3:'Puis-je partager une fusion ?',a3:'Oui. Chaque combinaison générée peut être ouverte avec une URL de fusion facile à copier et à partager.'},
 de:{title:'Pokémon Fusion Generator — Eigene Pokémon Fusionen erstellen',desc:'Erstelle online eigene Pokémon Fusionen. Kombiniere zwei Pokémon, generiere einen Fusionsnamen, lade dein Ergebnis herunter und teile es.',h1:'Pokémon Fusion Generator',intro:'Erstelle deine eigene Pokémon Fusion online, indem du zwei Pokémon kombinierst. Wähle deine Favoriten, erstelle eine Fusion, lade das Ergebnis herunter und teile es.',how:'So funktioniert der Pokémon Fusion Generator',howText:'Wähle zwei Pokémon aus dem Pokédex und erstelle sofort eine Fusion. Nutze zufällige Kombinationen für neue Ideen und teile deine Fusion über eine eigene URL.',what:'Was ist eine Pokémon Fusion?',whatText:'Eine Pokémon Fusion verbindet zwei Pokémon zu einem kreativen neuen Konzept. PokeFusion ist ein Fan-Projekt zum Experimentieren, Entdecken und Teilen von Fusionen.',faq:'Pokémon Fusion FAQ',q1:'Ist PokeFusion kostenlos?',a1:'Ja. Der PokeFusion Generator kann kostenlos direkt im Browser verwendet werden.',q2:'Kann ich zwei Pokémon kombinieren?',a2:'Ja. Suche im verfügbaren Pokédex nach Pokémon und wähle zwei davon für eine Fusion aus.',q3:'Kann ich eine Fusion teilen?',a3:'Ja. Für jede erzeugte Kombination gibt es eine übersichtliche Fusion-URL zum Kopieren und Teilen.'}
};
function App(){const lang=location.pathname.startsWith('/fr')?'fr':location.pathname.startsWith('/de')?'de':'en';const t=copy[lang];const [catalog,setCatalog]=useState([]),[a,setA]=useState(null),[b,setB]=useState(null),[qa,setQa]=useState(''),[qb,setQb]=useState(''),[result,setResult]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[dark,setDark]=useState(true),[copied,setCopied]=useState(false);
 useEffect(()=>{document.title=t.title;document.documentElement.lang=lang;let d=document.querySelector('meta[name="description"]');if(d)d.content=t.desc;},[lang,t]);
 useEffect(()=>{fetch(`${API}?limit=${TOTAL}`).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setCatalog(d.results.map((x,i)=>({name:x.name,id:i+1})));setLoading(false)}).catch(()=>{setCatalog(fallbackNames.map((name,i)=>({name,id:idFromName(name)||i+1})));setLoading(false);setError('Live Pokédex unavailable — using starter catalog.')})},[]);
 useEffect(()=>{const m=location.pathname.match(/\/pokemon-fusion\/([^/]+)-([^/]+)/);if(m&&catalog.length){const x=catalog.find(p=>p.name===m[1]),y=catalog.find(p=>p.name===m[2]);if(x&&y){setA(x);setB(y);setQa(x.name);setQb(y.name);setResult({a:x,b:y,name:fusionName(x,y),idA:x.id,idB:y.id})}}},[catalog]);
 const fa=useMemo(()=>filter(catalog,qa),[catalog,qa]),fb=useMemo(()=>filter(catalog,qb),[catalog,qb]);
 function generate(x=a,y=b){if(!x||!y){setError('Choose two Pokémon first.');return}setError('');setCopied(false);setResult({a:x,b:y,name:fusionName(x,y),idA:x.id,idB:y.id});history.replaceState({},'',`/pokemon-fusion/${x.name}-${y.name}`)}
 function random(){if(!catalog.length)return;const x=catalog[Math.floor(Math.random()*catalog.length)],y=catalog[Math.floor(Math.random()*catalog.length)];setA(x);setB(y);setQa(x.name);setQb(y.name);generate(x,y)}
 async function share(){if(!result)return;try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setError(location.href)}}
 function download(){if(!result)return;const c=document.createElement('canvas');c.width=1000;c.height=600;const x=c.getContext('2d');x.fillStyle='#090b18';x.fillRect(0,0,1000,600);x.fillStyle='#fff';x.font='700 42px Inter,Arial';x.fillText(result.name.toUpperCase(),55,75);Promise.all([loadImage(sprite(result.idA)),loadImage(sprite(result.idB))]).then(([ia,ib])=>{x.drawImage(ia,80,155,330,330);x.drawImage(ib,590,155,330,330);const l=document.createElement('a');l.download=`${result.name}.png`;l.href=c.toDataURL('image/png');l.click()}).catch(()=>setError('Could not create the download image.'))}
 return <div className={dark?'app dark':'app'}><header className="nav"><div className="brand"><span className="pokeball">◓</span><span>Poke<span>Fusion</span></span></div><nav><a href="#generator">Generator</a><a href="#how">How it works</a><a href="#explore">Explore</a><a href="/fr/">FR</a><a href="/de/">DE</a></nav><button className="icon" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?'☀':'☾'}</button></header>
 <main><section className="hero"><div className="eyebrow">POKÉMON FUSION LAB · {lang.toUpperCase()}</div><h1>{t.h1}</h1><p>{t.intro}</p><div className="hero-actions"><a className="primary" href="#generator">{lang==='fr'?'Commencer':lang==='de'?'Fusion starten':'Start fusing'} <span>→</span></a><button className="ghost" onClick={random}>⚡ {lang==='fr'?'Fusion aléatoire':lang==='de'?'Zufällige Fusion':'Random fusion'}</button></div></section>
 <section id="generator" className="panel"><div className="panel-head"><div><span className="step">01</span><h2>{lang==='fr'?'Choisissez vos Pokémon':lang==='de'?'Wähle deine Pokémon':'Choose your Pokémon'}</h2><p>{lang==='fr'?'Choisissez deux Pokémon et créez une fusion.':lang==='de'?'Wähle zwei Pokémon und erstelle eine Fusion.':'Pick two Pokémon and create a fusion.'}</p></div><button className="random" onClick={random}>⤨ Surprise me</button></div><div className="selectors"><Picker label="POKÉMON A" value={a} query={qa} setQuery={setQa} setValue={setA} items={fa} loading={loading}/><div className="plus">+</div><Picker label="POKÉMON B" value={b} query={qb} setQuery={setQb} setValue={setB} items={fb} loading={loading}/></div><button className="generate" onClick={()=>generate()}>{lang==='fr'?'Créer la fusion':lang==='de'?'Fusion erstellen':'Create fusion'} <span>✦</span></button>{error&&<div className="notice">{error}</div>}</section>
 {result&&<section className="result"><div className="result-copy"><span className="step">02 · RESULT</span><h2>{result.name}</h2><p>{result.a.name} + {result.b.name}</p><div className="result-actions"><button className="primary" onClick={download}>↓ Download</button><button className="ghost" onClick={share}>↗ {copied?'Copied!':'Share'}</button></div></div><div className="fusion-stage"><div className="orb orb-a"></div><div className="orb orb-b"></div><img src={sprite(result.idA)} alt={result.a.name}/><div className="fusion-mark">✦</div><img src={sprite(result.idB)} alt={result.b.name}/></div></section>}
 <section id="how" className="seo-copy"><h2>{t.how}</h2><p>{t.howText}</p><h2>{t.what}</h2><p>{t.whatText}</p><h2>{t.faq}</h2><h3>{t.q1}</h3><p>{t.a1}</p><h3>{t.q2}</h3><p>{t.a2}</p><h3>{t.q3}</h3><p>{t.a3}</p></section>
 <section id="explore" className="features"><Feature n="01" title="Pick two" text="Search the Pokédex and choose any pair."/><Feature n="02" title="Fuse instantly" text="Create a memorable fusion identity in seconds."/><Feature n="03" title="Share it" text="Download your result or copy its unique fusion URL."/></section></main><footer><div className="brand"><span className="pokeball">◓</span><span>Poke<span>Fusion</span></span></div><span>Fan-made fusion experience · Not affiliated with Nintendo, Game Freak or The Pokémon Company.</span></footer></div>}
function filter(items,q){if(!q)return items.slice(0,8);return items.filter(x=>x.name.includes(q.toLowerCase().trim())).slice(0,8)}
function Picker({label,value,query,setQuery,setValue,items,loading}){return <div className="picker"><label>{label}</label><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Pokémon..." aria-label={`Search ${label}`}/></div><div className="choices">{loading?<div className="empty">Loading Pokédex…</div>:items.map(x=><button className={value?.id===x.id?'choice active':'choice'} key={x.id} onClick={()=>{setValue(x);setQuery(x.name)}}><img src={sprite(x.id)} alt=""/><span>{x.name}</span><small>#{String(x.id).padStart(3,'0')}</small></button>)}{!loading&&!items.length&&<div className="empty">No Pokémon found.</div>}</div></div>}
function Feature({n,title,text}){return <article className="feature"><span>{n}</span><h3>{title}</h3><p>{text}</p></article>} function loadImage(src){return new Promise((r,j)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>r(i);i.onerror=j;i.src=src})} createRoot(document.getElementById('root')).render(<App/>);
